version: 2.1
orbs:
  macos: circleci/macos@2.3.6
  android: circleci/android@2.3.0
  node: circleci/node@5.1.0
  revenuecat: revenuecat/sdks-common-config@2.2.0

aliases:
  base-mac-job: &base-mac-job
    resource_class: macos.x86.medium.gen2
    macos:
      xcode: '14.3.0'
    shell: /bin/bash --login -o pipefail

  release-tags: &release-tags
    filters:
      tags:
        ignore: /^.*-SNAPSHOT/
      branches:
        ignore: /.*/

  release-branches: &release-branches
    filters:
      tags:
        ignore: /.*/
      branches:
        only: /^release\/.*/

  only-main-branch: &only-main-branch
    filters:
      tags:
        ignore: /.*/
      branches:
        only: main

parameters:
  action:
    type: enum
    enum: [build, upgrade-hybrid-common, bump]
    default: build
  version:
    type: string
    default: ''
  automatic:
    type: boolean
    default: false

commands:

  install-nvm:
    steps:
      - node/install:
          install-yarn: true

  yarn-dependencies-unix:
    description: "Install yarn dependencies"
    steps:
      - install-nvm
      - restore_cache:
          key: v2-unix-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-unix-dependencies-{{ checksum "package.json" }}

  yarn-dependencies-mac:
    description: "Install yarn dependencies"
    steps:
      - install-nvm
      - restore_cache:
          key: v2-mac-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-mac-dependencies-{{ checksum "package.json" }}

  install-sdkman:
    description: Install SDKMAN
    steps:
      - run:
          name: Installing SDKMAN
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Setup Java environment
          command: |
            sdk env install
            echo -e '\nexport JAVA_HOME="/home/circleci/.sdkman/candidates/java/current"' >> $BASH_ENV

  copy-npm-rc:
    steps:
      - run:
          name: Copy npmrc sample file to final location
          command: cp .npmrc.SAMPLE .npmrc

jobs:
  run-tests-ios:
    <<: *base-mac-job
    steps:
      - checkout
      - revenuecat/install-gem-mac-dependencies:
          cache-version: v1
      - yarn-dependencies-mac
      - run: yarn build
      - run: yarn verify:ios

  run-tests-android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.06.1
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - yarn-dependencies-unix
      - run: yarn build
      - run: yarn verify:android

  build-purchase-tester:
    <<: *base-mac-job
    steps:
      - checkout
      - revenuecat/install-gem-mac-dependencies:
          cache-version: v1
      - yarn-dependencies-mac
      - run:
          name: Build purchase tester
          command: bundle exec fastlane build_purchase_tester


  run-lint:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - yarn-dependencies-unix
      - run: yarn build
      - run: yarn lint

  make-release:
    description: "Publishes the new version and creates a github release"
    <<: *base-mac-job
    steps:
      - checkout
      - revenuecat/install-gem-mac-dependencies:
          cache-version: v1
      - yarn-dependencies-mac
      - revenuecat/trust-github-key
      - copy-npm-rc
      - run:
          name: release
          command: bundle exec fastlane release

  update-hybrid-common-versions:
    description: "Creates a PR updating purchases-hybrid-common to latest release"
    <<: *base-mac-job
    steps:
      - checkout
      - revenuecat/install-gem-mac-dependencies:
          cache-version: v1
      - revenuecat/trust-github-key
      - revenuecat/setup-git-credentials
      - run:
          name: Updating to next version of phc
          command: |
            bundle exec fastlane update_hybrid_common \
            version:<< pipeline.parameters.version >> \
            open_pr:true \
            automatic_release:<< pipeline.parameters.automatic >>

  # Note this is not using the orb's automatic-bump job since we need to install yarn to update docs here.
  bump:
    description: >
      Runs automatic bump
    docker:
      - image: cimg/ruby:3.1.2
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - revenuecat/trust-github-key
      - revenuecat/setup-git-credentials
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - yarn-dependencies-unix
      - run:
          name: Create automatic PR
          command: bundle exec fastlane automatic_bump github_rate_limit:10

workflows:
  version: 2
  build-test:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - run-tests-ios
      - run-tests-android
      - run-lint
      - build-purchase-tester

  deploy:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - run-tests-ios:
          <<: *release-branches
      - run-tests-android:
          <<: *release-branches
      - run-lint:
          <<: *release-branches
      - hold:
          type: approval
          requires:
            - run-tests-ios
            - run-tests-android
            - run-lint
          <<: *release-branches
      - revenuecat/tag-current-branch:
          requires:
            - hold
          <<: *release-branches
      - make-release:
          <<: *release-tags

  danger:
    jobs:
      - revenuecat/danger

  weekly-run-workflow:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "release-train", << pipeline.schedule.name >> ]
    jobs:
      - bump

  manual-trigger-bump:
    when:
      equal: [ bump, << pipeline.parameters.action >> ]
    jobs:
      - bump

  update-hybrid-common-versions:
    when:
      equal: [ upgrade-hybrid-common, << pipeline.parameters.action >> ]
    jobs:
      - update-hybrid-common-versions
